name: postgresql
config_catalog: migration_catalog
config_schema: config_schema
config_table: config_pgsql
logging_catalog: migration_catalog
logging_schema: logging
log_table: migration_log_pgsql
job_logs_table: job_logs_pgsql
validation_catalog: migration_catalog
validation_schema: validation_schema
validation_table: validation_log_pgsql
data_quality_catalog: migration_catalog
data_quality_schema: dataquality_schema
data_quality_table: data_quality_log_pgsql
secrets_scope: AutoDbx
jdbc_driver: org.postgresql.Driver
secrets:
  host: pgsql_host
  port: pgsql_port
  user: pgsql_user
  password: pgsql_password