"""Initial migration

Revision ID: 9ffb9d4f5f46
Revises: 
Create Date: 2026-04-22 15:11:49.754562

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ffb9d4f5f46'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('source_csv',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_csv_id'), 'source_csv', ['id'], unique=False)
    op.create_table('migration',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'SUCCESS', 'FAILED', name='migrationstatus'), nullable=False),
    sa.Column('validate_bundle_status', sa.Enum('PENDING', 'RUNNING', 'SUCCESS', 'FAILED', name='migrationstatus'), nullable=True),
    sa.Column('validate_bundle_meta_data', sa.JSON(), nullable=True),
    sa.Column('validate_start_time', sa.DateTime(), nullable=True),
    sa.Column('validate_completion_time', sa.DateTime(), nullable=True),
    sa.Column('deploy_bundle_status', sa.Enum('PENDING', 'RUNNING', 'SUCCESS', 'FAILED', name='migrationstatus'), nullable=True),
    sa.Column('deploy_bundle_meta_data', sa.JSON(), nullable=True),
    sa.Column('deploy_start_time', sa.DateTime(), nullable=True),
    sa.Column('deploy_completion_time', sa.DateTime(), nullable=True),
    sa.Column('config_table_status', sa.Enum('PENDING', 'RUNNING', 'SUCCESS', 'FAILED', name='migrationstatus'), nullable=True),
    sa.Column('config_table_meta_data', sa.JSON(), nullable=True),
    sa.Column('config_table_start_time', sa.DateTime(), nullable=True),
    sa.Column('config_table_completion_time', sa.DateTime(), nullable=True),
    sa.Column('migration_job_status', sa.Enum('PENDING', 'RUNNING', 'SUCCESS', 'FAILED', name='migrationstatus'), nullable=True),
    sa.Column('migration_job_meta_data', sa.JSON(), nullable=True),
    sa.Column('migration_job_start_time', sa.DateTime(), nullable=True),
    sa.Column('migration_job_completion_time', sa.DateTime(), nullable=True),
    sa.Column('source_csv_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['source_csv_id'], ['source_csv.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_migration_id'), 'migration', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_migration_id'), table_name='migration')
    op.drop_table('migration')
    op.drop_index(op.f('ix_source_csv_id'), table_name='source_csv')
    op.drop_table('source_csv')
    # ### end Alembic commands ###
